def normalize_text(text):
    """
    Chuẩn hóa một số teencode phổ biến trong tiếng Việt về tiếng Việt chuẩn.
    Ví dụ: 'k' => 'không', 'bt' => 'bình thường', 'huhu' => 'buồn', ...
    """
    import re

    teencode_dict = {
        'k': 'không',
        'khong': 'không',
        'hok': 'không',
        'ko': 'không',
        'hem': 'không',
        'bt': 'bình thường',
        'bthg': 'bình thường',
        'bth': 'bình thường',
        'thg': 'thường',
        'uk': 'ừ',
        'uh': 'ừ',
        'uhm': 'ừ',
        'okie': 'ok',
        'oke': 'ok',
        'oki': 'ok',
        'vs': 'với',
        'mik': 'mình',
        'mìnhk': 'mình không',
        'mjnh': 'mình',
        'mj': 'mình',
        'j': 'gì',
        'zi': 'gì',
        's': 'sao',
        'saoo': 'sao',
        'bik': 'biết',
        'bít': 'biết',
        'bit': 'biết',
        'hok': 'không',
        'vk': 'vợ',
        'ck': 'chồng',
        'dc': 'được',
        'đc': 'được',
        'dk': 'đăng ký',
        'r': 'rồi',
        'rùi': 'rồi',
        'rùi nè': 'rồi nè',
        'sz': 'size',
        'h': 'giờ',
        'hny': 'hôm nay',
        'lm': 'làm',
        'ad': 'admin',
        'ib': 'inbox',
        'inb': 'inbox',
        'inb mình': 'inbox mình',
        'rep': 'trả lời',
        'lh': 'liên hệ',
        'lhệ': 'liên hệ',
        'mt': 'mặt tiền',
        'thik': 'thích',
        'thíc': 'thích',
        'tkh': 'thích',
        'tm': 'thôi mà',
        'tks': 'cảm ơn',
        'thank': 'cảm ơn',
        'thanks': 'cảm ơn',
        'tks nhìu': 'cảm ơn nhiều',
        'z': 'giờ',
        'vl': 'vãi',
        'vlz': 'vãi l',
        'cay vl': 'rất tức',
        'zui': 'vui',
        'dzui': 'vui',
        'huhu': 'buồn',
        'hjx': 'buồn',
        'hix': 'buồn',
        'buồn vãi': 'rất buồn',
        'zzz': 'ngủ',
        'ngủm': 'ngủ',
        'cute': 'dễ thương',
        'cưng': 'dễ thương',
        'cưng xỉu': 'dễ thương lắm',
        'dễ thg': 'dễ thương',
        'sdt': 'số điện thoại',
        'dt': 'điện thoại',
        'add': 'thêm',
        'ae': 'anh em',
        'a e': 'anh em',
        'aeo': 'anh em ơi',
        'bạn mìn': 'bạn mình',
        'ckoi': 'cái gì',
        'bn': 'bạn',
        'bnk': 'bạn không',
        'bestie': 'bạn thân',
        'ms': 'mới',
        'msn': 'messenger',
        'nx': 'nhận xét',
        'nxk': 'nhận xét',
        'nxj': 'nhận xét',
        'ny': 'người yêu',
        'nyc': 'người yêu cũ',
        'crush': 'người thầm thích',
        'oppa': 'anh trai',
        'unnie': 'chị gái',
        'idol': 'thần tượng',
        'qtv': 'quản trị viên',
        'qtvđ': 'quá trời quá đất',
        'qtq': 'quá trời quá đất',
        'qtqđ': 'quá trời quá đất',
        'ptit': 'học viện công nghệ bưu chính viễn thông',
        'kt': 'kiểm tra',
        'ktv': 'kỹ thuật viên',
        'ktx': 'ký túc xá',
        'thamkhao': 'tham khảo',
        'tham khảo': 'tham khảo',
        'trc': 'trước',
        'truoc': 'trước',
        'stt': 'status',
        'status': 'trạng thái',
        'avt': 'avatar',
        'avata': 'avatar',
        'avarta': 'avatar',
        'thớt': 'chủ thớt',
        'chủ thot': 'chủ thớt',
        'mod': 'người kiểm duyệt',
        'save': 'lưu lại',
        'saved': 'đã lưu',
        'msv': 'mã sinh viên',
        'id': 'số định danh',
        'cxr': 'cũng rứa',
        'nv': 'nhân vật',
        'nvien': 'nhân viên',
        'pa': 'phương án',
        'pf': 'profile',
        'pro5': 'profile',
        'pro': 'pro',
        'xjn': 'xin',
        'xin nè': 'xin',
        'xin nha': 'xin',
        'đk': 'đăng ký',
        'đky': 'đăng ký',
        'kb': 'kết bạn',
        'kb liền': 'kết bạn liền',
        'kết b': 'kết bạn',
        'vđ': 'vấn đề',
        'ko biết': 'không biết',
        'k biet': 'không biết',
        'clm': 'cười lộn mề',
        'cmnr': 'chuẩn bị rồi',
        'cmt': 'bình luận',
        'cmtđ': 'bình luận đi',
        'cmt nha': 'bình luận đi',
        'cmt ik': 'bình luận đi',
        'bl': 'bình luận',
        'blv': 'bình luận viên',
        'bl nhé': 'bình luận nhé',
        'vjp': 'đẹp',
        'vjp pro': 'rất đẹp',
        'pro vjp': 'rất đẹp',
        'cr': 'credit',
        'cf': 'cà phê',
        'cf sữa': 'cà phê sữa',
        'mtq': 'mạnh thường quân',
        'sn': 'sinh nhật',
        'snvv': 'sinh nhật vui vẻ',
        'kb đi': 'kết bạn đi',
        'nt': 'nhắn tin',
        'nti': 'nhắn tin',
        'nhan tin': 'nhắn tin',
        'tđn': 'tên đăng nhập',
        'tn': 'tin nhắn',
        'tin nhan': 'tin nhắn',
        'dm': 'địt mẹ',
        'dmk': 'đổi mật khẩu',
        'cc': 'con cặc',
        'vc': 'vãi chưởng',
        'mxh': 'mạng xã hội',
        'tt': 'thông tin',
        'tk': 'tài khoản',
        'ac': 'tài khoản',
        'nick': 'tài khoản',
        'sp': 'sản phẩm',
        'sp mới': 'sản phẩm mới',
        'đú': 'bắt trend',
        'đu trend': 'bắt trend',
        'trend': 'xu hướng',
        'fail': 'thất bại',
        'fake': 'giả mạo',
        'out': 'rời đi',
        'onl': 'online',
        'ofl': 'offline',
        'on': 'online',
        'off': 'offline',
        'hi': 'chào',
        'hii': 'chào',
        'hí': 'chào',
        'helo': 'chào',
        'helloo': 'chào',
        'alo': 'alo',
        'alô': 'alo',
        'yo': 'chào',
        'xin chào': 'chào',
        'bye': 'tạm biệt',
        'bibi': 'tạm biệt',
        'bb': 'bye bye',
        'lub': 'love',
        'tym': 'tim',
        'tym tym': 'trái tim',
        'tym to': 'trái tim to',
        'tym nhỏ': 'trái tim nhỏ',
        'vcđ': 'vãi cả đái',
        'vcl': 'vãi cả lúa',
        'vclo': 'vãi cả lồn',
        'vcc': 'vãi cả cứt',
        'dth': 'dễ thương',
        'dẹo': 'dẻo',
        'max': 'nhiều',
        'max ghê': 'nhiều quá',
        'đú trend': 'bắt trend',
        'bựa': 'vui nhộn',
        'vãi chưởng': 'rất bất ngờ',
        'tp': 'thành phố',
        'mlem': 'ngon',
        'chx': 'chưa',
        'chua': 'chưa',
        'hnay': 'hôm nay',
        'mai': 'ngày mai',
        'mốt': 'ngày mốt',
        'hn': 'hà nội',
        'sg': 'sài gòn',
        'hcm': 'thành phố hồ chí minh',
        'huế': 'thừa thiên huế',
        'ct': 'cần thơ',
        'nha': 'nhé',
        'nhaaa': 'nhé',
        'akh': 'anh không',
        'emk': 'em không',
        'okela': 'ok',
        'okla': 'ok',
        'oke la': 'ok',
        'kute': 'dễ thương',
        'dz': 'đẹp trai',
        'dzai': 'đẹp trai',
        'dzưa': 'dưa',
        'đz': 'đẹp trai',
        'thớt': 'chủ thớt',
        'sao': 'tại sao',
        'sm': 'sao mà',
        'hdsd': 'hướng dẫn sử dụng',
        'hd': 'hướng dẫn',
        'hdd': 'hướng dẫn',
        'cg': 'cái gì',
        'clgt': 'cái l',
        'gì thế': 'cái gì vậy',
        'max': 'nhiều',
        'vp': 'văn phòng',
        'st': 'sưu tầm',
        'stth': 'status',
        'ttin': 'thông tin',
        'dt': 'điện thoại',
        'sdt': 'số điện thoại',
        'bv': 'bài viết',
        'kv': 'khu vực',
        'mk': 'mật khẩu',
        'pass': 'mật khẩu',
        'passw': 'mật khẩu',
        'nv': 'nhân vật',
        'avt': 'avatar',
        'tim': 'trái tim',
        'love': 'tình yêu',
        'ty': 'tình yêu',
        'yêu thương': 'tình yêu',
        'bff': 'best friend forever',
        'ik': 'đi',
        'đi ik': 'đi đi',
        'njk': 'nhưng',
        'khỉ gió': 'đùa thôi',
        'kkk': 'cười',
        'kk': 'cười',
        'haizz': 'thở dài',
        'sml': 'sấp mặt luôn',
        'bái bai': 'tạm biệt',
        'sayhi': 'chào',
        'say hi': 'chào',
        'rep ib': 'trả lời inbox',
        'rep tin nhắn': 'trả lời tin nhắn',
        'in4': 'thông tin',
        'in tư': 'thông tin',
        'hot boy': 'chàng trai đẹp',
        'hot girl': 'cô gái đẹp',
        'gái xinh': 'con gái đẹp',
        'trai xinh': 'chàng trai đẹp',
        'oke luôn': 'đồng ý ngay',
        'đú': 'bắt trend',
        'anti': 'phản đối',
        'fl': 'theo dõi',
        'fol': 'theo dõi',
        'ibee': 'inbox',
        'ib liền': 'inbox liền',
        'loz': 'lồn',
        'ngta': 'người ta',
        'bktr': 'bạn cùng trường',
        'mắc cười': 'buồn cười',
        'chịu thua': 'bó tay',
        'chịu luôn': 'bó tay',
        'toos': 'tới',
        'g9': 'good night',
        'g8': 'good night',
        'g7': 'good night',
        'g10': 'good morning',
        'gm': 'good morning',
        'bh': 'bao giờ',
        'bao h': 'bao giờ',
        'mng': 'mọi người',
        'mn': 'mọi người',
        'mọi ng': 'mọi người',
        'gấu': 'người yêu',
        'chộp': 'chụp',
        'chụp choẹt': 'chụp ảnh',
        'chụtt': 'chụt',
        'huhu': 'buồn',
        'tht': 'thật',
        'oa': 'wow',
        'wow': 'ngạc nhiên',
        'dzo': 'vô',
        'vô luôn': 'vào luôn',
        'đú trend': 'bắt trend',
        'phượt': 'du lịch bụi',
        'bắn tim': 'gửi trái tim',
        'gato': 'ghen ăn tức ở',
        'ghen tỵ': 'gato',
        'gắt': 'nóng quá',
        'vinh dự': 'vinh dự',
        'cao thủ': 'giỏi',
        'troll': 'chơi khăm',
        'troll nhau': 'chơi khăm nhau',
        'op': 'original poster',
        'lv': 'level',
        'lvmax': 'level cao nhất',
        'cj': 'chị',
        'ac': 'anh chị',
        'ace': 'anh chị em',
        'bxh': 'bảng xếp hạng',
        'sttu': 'status',
        'sup': 'xin chào',
        'xjn': 'xin',
        'dzo': 'vào',
        'tặng kèm': 'kèm theo',
        'ới': 'ơi',
        'ơi bạn': 'bạn ơi',
        'kkk': 'cười',
        'smile': 'cười',
        'gửi ảnh': 'gửi hình',
        'chém gió': 'nói khoác',
        'mod': 'người kiểm duyệt',
        'checkin': 'ghi nhận vị trí',
        'check-in': 'ghi nhận vị trí',
        'vs': 'với',
        'wá': 'quá',
        'wa': 'quá',
        'chill': 'thư giãn',
        'cày cuốc': 'làm việc chăm chỉ',
        'msn': 'messenger',
        'tl': 'trả lời',
        'reply': 'trả lời',
        'zt': 'zalo',
        'zca': 'zalo cả',
        'zn': 'zalo nhé',
        'zc': 'zalo',
        'ctr': 'chương trình',
        'dcj': 'được chứ',
        'ko sao': 'không sao',
        'ttin': 'thông tin',
        'sumo': 'mạnh mẽ',
        'chuẩn men': 'đàn ông',
        'chuẩn men luôn': 'rất đàn ông',
        'fail cmn': 'thất bại hoàn toàn',
    }

    # Sắp xếp từ dài nhất trước để tránh thay thế nhầm các từ ngắn nằm trong từ dài
    sorted_teencodes = sorted(teencode_dict.items(), key=lambda x: -len(x[0]))

    # Hàm thay thế từng từ
    def replace(match):
        word = match.group(0)
        lower_word = word.lower()
        for tk, replacement in sorted_teencodes:
            if lower_word == tk:
                return replacement
        return word

    # Sử dụng regex để thay thế từng từ
    pattern = re.compile(r'\b(' + '|'.join(re.escape(k) for k in teencode_dict.keys()) + r')\b', re.IGNORECASE)
    normalized_text = pattern.sub(lambda m: teencode_dict[m.group(0).lower()], text)
    return normalized_text

